### PR TITLE
Upgrade address-formatting dependency

### PR DESCRIPTION
**Pull request by jscheid**
Hi, do you accept PRs? This one upgrades the dependency and makes all tests pass.

### CODE REVIEW

**Review by freyfogle — APPROVED** [review]
LGTM

**Comment by mirubiri** [comment]
Ey! Sorry I haven't seen the notification of this PR

**Comment by jscheid** [comment]
Hi @AlexArrufat, no problem. May I ask why you closed it without merging?

**Comment by jscheid** [comment]
Ah, I just realized that I've added commits to our branch that weren't intended for this PR. If I open a new PR without e16b057, would you accept it?

**Comment by AlexArrufat** [comment]
@jscheid yeah, exactly that was the reason. Sure, open a new one and I will accept it 😊

**Pull request closed without merging**
